### ISSUE TITLE
Whitespaces in query parameters don't get decoded during binding

### ISSUE THREAD

**Issue by imranazad** [openrasta/openrasta-core#191]
In OpenRasta 2.1 white spaces in query parameters don't get decoded during binding. I've pin pointed the issue to this line: https://github.com/openrasta/openrasta-core/blob/2.1/src/OpenRasta/UriTemplate.cs#L69

I just want to double check my findings. I think the use of `Uri.UnescapeDataString(value);` is too aggressive instead it should be `HttpUtility.UrlDecode(queries);`

Query parameter values: `Alopecia+reaction %2Bcancer`
Binded value: `Alopecia+reaction +cancer`
Correct value should be:  `Alopecia reaction +cancer`

I'm happy to open a pull request but just need someone to confirm my findings first.

Thanks

**Comment by serialseb** [comment]
Hi there! Thanks for the feedback. 2.1 is a very old codebase we don't maintain anymore: there isn o  nuget release, and the last trace of commits on that codebase is in 2011.

That said: `HttpUtility` is in a package that openrasta doesn't purposefully depend on, so we don't use that.

But if you look at the code in more recent versions, the plus in querystrings is transformed first before unescaping the percent encoded entries, which you can see in  https://github.com/openrasta/openrasta-core/blob/baba598ef945a8c9f19a8dca68bcc909793e45eb/src/OpenRasta/UriTemplate.cs#L132

Looking into it, I can see https://github.com/openrasta/openrasta-core/pull/48 that alluded to the same issue, so it is indeed fixed in the 2.5+ releases.

Hope  this  helps, and thanks again for letting us know!

**Comment by serialseb** [comment]
I'm going to go ahead and mark this issue as closed. If you want to reopen it, feel free to do so.

**Comment by imranazad** [comment]
@serialseb That's great thanks. I am curious why Uri.UnescapeDataString has been used instead of HttpUtility.UrlDecode? I'm currently using HttpUtility.UrlDecode and wondered if I've missed something by using this.
