### ISSUE TITLE
Handler methods in a base class with multiple implementors throw exceptions

### ISSUE THREAD

**Issue by hanksjosholo** [openrasta/openrasta-core#197]
In our application we have 2 handlers that have the same base class.  Configuration is set up using `.Named("")` to distinguish between them. Upon upgrading from 2.5 to 2.6, those endpoints return 500 errors. I was able to repro this in a simple project here https://github.com/hanksjosholo/OpenRastaTester using `2.6.0-preview.2`.

I did some debugging, and it looks like the `HandlerResolverContributor` here   https://github.com/openrasta/openrasta-core/blob/73841c032f8abc6013e1c48a8820b2d2550a9d23/src/OpenRasta/Pipeline/Contributors/HandlerResolverContributor.cs#L27 calls the `HandlerRepository` and here https://github.com/openrasta/openrasta-core/blob/73841c032f8abc6013e1c48a8820b2d2550a9d23/src/OpenRasta/Handlers/HandlerRepository.cs#L43 the `resourceHandlers` dictionary contains two entries for the type. 

Those don't ever get filtered down, and by the time they get to the `RequestEntityReadyHydrator.VerifySingleMatch` here https://github.com/openrasta/openrasta-core/blob/73841c032f8abc6013e1c48a8820b2d2550a9d23/src/OpenRasta/OperationModel/Hydrators/RequestEntityReaderHydrator.cs#L62, there's still 2 operations, and the exception is thrown.

**Comment by serialseb** [comment]
Need to add notifications to our slack so i don't lose track of those. Good catch, thanks for that!

**Comment by serialseb** [comment]
I did some investigation, but I think it's either a configuration problem or a repro problem.

Whenever you register .ResourcesOfType<>, OpenRasta considers that you want to add things to a resource of type T, here `Animal`. Every time you add a Uri.Named, you add a URI and we pass the uri name down the line for processing. Every time you add a handler, we add an extra handler type to that resource `Animal`.

In 2.5 we would randomly select whichever first handler comes when there's no way to disambiguate, leading to issues where container registration ordering, or various versions of dotnet, would result in different methods being called. We no longer do that as this has caused issues over time for customers trying to migrate from version to version.

So in this configuration, OpenRasta seens two handler methods, one for `CatHandler.Get` and one for `DogHandler.Get`, and there is no way to know which one can map to the two incoming uris, because they look the same structurally.

When you use .Named on a URI, we pass it along in the request, but it also impacts how we match the methods. There's two ways currently that we discriminate in the presence of a uri name:
1. By convention, GetCat, where Get is the method and Cat is the uri name in the configuration
2. By attribute, `HttpOperation(ForUriName="cat")`

You have a few options:
1. Register a Cat and a Dog type independently, and you will be able to register as usual, but for distinct registrations
2. Register cat and dog as named resources, rather than typed ones. `ResourcesNamed("cat").AtUri("/cat").HandledBy<AnimalHandler>()` would do it. You do lose some type safety and func-based configuration, but each resource will indeed be independent.
3. Register Animal twice but give the resource itself a name. That's new in `master` and allows discriminating multiple type registrations. Syntax is `ResourcesOfType<Animal>().Named("cat")`. It will correctly register two different resources instead of register the same resource twice.

Hope it helps.
