### ISSUE TITLE
UriTemplate & encoded URIs

### ISSUE THREAD

**Issue by cangencer** [openrasta/openrasta-core#46]
Currently the UriTemplate class does not do any kind of URI encoding when doing BindingByName. 

Here is a test that will fail

``` csharp
BindingUriByName("/{value}", new { value = "?query" }).ShouldAllBe("http://localhost/foo/%3Fquery");
```

Are the consumers of the class, such as when using object.CreateUri(), expected to supply Uri Escaped Values?

**Comment by serialseb** [comment]
I've reviewed  this case and I'm not sure that we should be encoding this case at all, there would be no way for  us to make much  sense of  when to encode a ? vs not encoding it. After  all, index?query=?may be a valid URI, as the abnf specifies `query         = *( pchar / "/" / "?" )`

What I have however done is make sure the uri templates can roundtrip by encoding the separators that would break things otherwise.

Let me kno if that doesn't address your problem
