### ISSUE TITLE
Transfer-Encoding: chunked returns unsupported media type

### ISSUE THREAD

**Issue by peteog** [openrasta/openrasta-core#60]
Transfer-Encoding: chunked returns unsupported media type

I have a handler that I'm sending a PUT request to with some data.

```
curl -i http://example.com/ -X PUT -d "Some text" --header "Content-Type: text/plain"
> HTTP/1.1 200 OK
```

If I add a `Transfer-Encoding: chunked` header I get a 415

```
curl -i http://example.com/ -X PUT -d "Some text" --header "Content-Type: text/plain" --header "Transfer-Encoding: chunked"
> HTTP/1.1 415 Unsupported Media Type
```

I've tracked it down to this line: https://github.com/openrasta/openrasta-core/blob/master/src/OpenRasta/OperationModel/CodecSelectors/RequestCodecSelector.cs#L31

In the chunked instance the ContentLength is null

**Comment by serialseb** [comment]
Hi there.

Thanks for reporting this issue! It's awesome of you to have taken the time.

It seems that this issue is also part of the #101 issue.

In the interest of keeping our backlog lean as a 🌤, I'm closing the issue in favour of the other one. If you feel this is not right, don't hesitate to comment and/or reopen the issue.

Thanks!
